### PR TITLE
add kangaroo solution using php

### PR DESCRIPTION
**Pull request by mush60**

### CODE REVIEW

**Comment by vichitr** [comment]
Is Kangaroo a platform? If not then put the file in appropriate folder only.

**Comment by mush60** [comment]
> Is Kangaroo a platform? If not then put the file in appropriate folder only.

Kangaroo is a problem at hackerrank

**Comment by vichitr** [comment]
Then you should put in Hackerrank folder. Don't create new folder for particular problem.

**Comment by mush60** [comment]
> Then you should put in Hackerrank folder. Don't create new folder for particular problem.

sorry, this is my first tima as contributor, btw can u give me label as hacktober too?

**Comment by vichitr** [comment]
> 
> 
> > Then you should put in Hackerrank folder. Don't create new folder for particular problem.
> 
> sorry, this is my first tima as contributor, btw can u give me label as hacktober too?

Don't worry! This PR will contribute to your progress in Hacktoberfest.

**Pull request merged**
